/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BIrGmNnmAC2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState, useEffect, JSX, SVGProps } from "react"
import Link from "next/link"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"

export function Jobs() {
  const [theme, setTheme] = useState("light")
  useEffect(() => {
    const root = document.documentElement
    if (theme === "dark") {
      root.classList.add("dark")
    } else {
      root.classList.remove("dark")
    }
  }, [theme])
  return (
    <div className={`flex flex-col min-h-dvh ${theme === "dark" ? "dark" : ""}`}>
      <header className="bg-primary text-primary-foreground px-4 lg:px-6 h-14 flex items-center">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <BoxIcon className="size-6" />
          <span className="sr-only">Acme Construction Staffing</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Job Board
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Employee Dashboard
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Admin Panel
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Contact
          </Link>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" size="icon" className="rounded-full">
                {theme === "dark" ? <SunIcon className="w-5 h-5" /> : <MoonIcon className="w-5 h-5" />}
                <span className="sr-only">Toggle theme</span>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem onSelect={() => setTheme("light")}>Light</DropdownMenuItem>
              <DropdownMenuItem onSelect={() => setTheme("dark")}>Dark</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full pt-12 md:pt-24 lg:pt-32 border-y">
          <div className="px-4 md:px-6 space-y-10 xl:space-y-16">
            <div className="grid max-w-[1300px] mx-auto gap-4 px-4 sm:px-6 md:px-10 md:grid-cols-2 md:gap-16">
              <div>
                <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                  Find the best construction talent, fast.
                </h1>
                <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl">
                  Acme Construction Staffing connects you with skilled professionals to power your projects.
                </p>
                <div className="space-x-4 mt-6">
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    View Job Board
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Contact Us
                  </Link>
                </div>
              </div>
              <div className="flex flex-col items-start space-y-4">
                <img
                  src="/placeholder.svg"
                  width="600"
                  height="400"
                  alt="Construction Workers"
                  className="rounded-lg object-cover"
                  style={{ aspectRatio: "600/400", objectFit: "cover" }}
                />
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Featured Jobs</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Explore our latest openings</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Browse our job board to find the perfect fit for your construction project.
                </p>
              </div>
            </div>
            <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
              <Card>
                <CardHeader>
                  <CardTitle>Project Manager</CardTitle>
                  <CardDescription>San Francisco, CA</CardDescription>
                </CardHeader>
                <CardContent>
                  <p className="text-sm/relaxed">
                    Experienced project manager needed to oversee a multi-million dollar commercial construction
                    project. Strong leadership and communication skills required.
                  </p>
                </CardContent>
                <CardFooter>
                  <Button size="sm">Apply Now</Button>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Site Superintendent</CardTitle>
                  <CardDescription>Los Angeles, CA</CardDescription>
                </CardHeader>
                <CardContent>
                  <p className="text-sm/relaxed">
                    Seeking a seasoned site superintendent to manage daily operations and coordinate subcontractors on a
                    large-scale commercial build.
                  </p>
                </CardContent>
                <CardFooter>
                  <Button size="sm">Apply Now</Button>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Electrician</CardTitle>
                  <CardDescription>San Diego, CA</CardDescription>
                </CardHeader>
                <CardContent>
                  <p className="text-sm/relaxed">
                    Experienced commercial electrician needed to join our team on a new office complex project. Must
                    have a valid electrical license and 5+ years of experience.
                  </p>
                </CardContent>
                <CardFooter>
                  <Button size="sm">Apply Now</Button>
                </CardFooter>
              </Card>
            </div>
            <div className="flex justify-center">
              <Link
                href="#"
                className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                prefetch={false}
              >
                View All Jobs
              </Link>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted dark:bg-[#1a1b1e]">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Empower Your Construction Workforce
              </h2>
              <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-muted-foreground">
                Our comprehensive employee dashboard gives your team the tools they need to stay productive and
                connected.
              </p>
            </div>
            <div className="flex flex-col gap-4 w-full max-w-4xl">
              <Card className="dark:bg-[#1f2023] dark:text-muted-foreground">
                <CardHeader>
                  <CardTitle>Project Management</CardTitle>
                  <CardDescription>View your current project assignments, timelines, and progress.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <h3 className="text-lg font-bold">Current Projects</h3>
                      <ul className="space-y-2 mt-2">
                        <li>
                          <div className="font-medium">Office Complex</div>
                          <div className="text-sm text-muted-foreground dark:text-muted-foreground">
                            San Francisco, CA
                          </div>
                        </li>
                        <li>
                          <div className="font-medium">Retail Center</div>
                          <div className="text-sm text-muted-foreground dark:text-muted-foreground">
                            Los Angeles, CA
                          </div>
                        </li>
                      </ul>
                    </div>
                    <div>
                      <h3 className="text-lg font-bold">Timesheets</h3>
                      <div className="space-y-2 mt-2">
                        <div className="flex items-center justify-between">
                          <div>Week of 4/3/2023</div>
                          <div className="font-medium">40 hrs</div>
                        </div>
                        <div className="flex items-center justify-between">
                          <div>Week of 3/27/2023</div>
                          <div className="font-medium">42 hrs</div>
                        </div>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card className="dark:bg-[#1f2023] dark:text-muted-foreground">
                <CardHeader>
                  <CardTitle>Attendance</CardTitle>
                  <CardDescription>
                    Track your clock-in and clock-out times, as well as any absences or late arrivals.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <h3 className="text-lg font-bold">This Week</h3>
                      <div className="space-y-2 mt-2">
                        <div className="flex items-center justify-between">
                          <div>Monday</div>
                          <div className="font-medium">8:00am - 5:00pm</div>
                        </div>
                        <div className="flex items-center justify-between">
                          <div>Tuesday</div>
                          <div className="font-medium">8:00am - 5:00pm</div>
                        </div>
                        <div className="flex items-center justify-between">
                          <div>Wednesday</div>
                          <div className="font-medium">8:00am - 5:00pm</div>
                        </div>
                      </div>
                    </div>
                    <div>
                      <h3 className="text-lg font-bold">Absences</h3>
                      <div className="space-y-2 mt-2">
                        <div className="flex items-center justify-between">
                          <div>Sick Day</div>
                          <div className="font-medium">4/5/2023</div>
                        </div>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Manage Your Construction Workforce
              </h2>
              <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-muted-foreground">
                Our admin panel gives you complete control over your construction staffing needs.
              </p>
            </div>
            <div className="flex flex-col gap-4 w-full max-w-4xl">
              <Card className="dark:bg-[#1f2023] dark:text-muted-foreground">
                <CardHeader>
                  <CardTitle>Employee Management</CardTitle>
                  <CardDescription>
                    Easily view and update employee profiles, skills, and project assignments.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <h3 className="text-lg font-bold">Active Employees</h3>
                      <ul className="space-y-2 mt-2">
                        <li>
                          <div className="font-medium">John Doe</div>
                          <div className="text-sm text-muted-foreground dark:text-muted-foreground">
                            Project Manager
                          </div>
                        </li>
                        <li>
                          <div className="font-medium">Jane Smith</div>
                          <div className="text-sm text-muted-foreground dark:text-muted-foreground">
                            Site Superintendent
                          </div>
                        </li>
                        <li>
                          <div className="font-medium">Michael Johnson</div>
                          <div className="text-sm text-muted-foreground dark:text-muted-foreground">Electrician</div>
                        </li>
                      </ul>
                    </div>
                    <div>
                      <h3 className="text-lg font-bold">Timekeeping</h3>
                      <div className="space-y-2 mt-2">
                        <div className="flex items-center justify-between">
                          <div>John Doe</div>
                          <div className="font-medium">40 hrs</div>
                        </div>
                        <div className="flex items-center justify-between">
                          <div />
                        </div>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

function BoxIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z" />
      <path d="m3.3 7 8.7 5 8.7-5" />
      <path d="M12 22V12" />
    </svg>
  )
}


function MoonIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z" />
    </svg>
  )
}


function SunIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41 1.41" />
      <path d="m17.66 17.66 1.41 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </svg>
  )
}
